// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBRv0UaZiKa8rYzjVyJDjS8DL3TheJfy8',
    appId: '1:725605393327:web:07944f52e3fb0c0e80c55a',
    messagingSenderId: '725605393327',
    projectId: 'scientific-research-eb4e5',
    authDomain: 'scientific-research-eb4e5.firebaseapp.com',
    storageBucket: 'scientific-research-eb4e5.firebasestorage.app',
    measurementId: 'G-R8PG0VFMMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0MZPcktY3jmdSgjLySupe8m_csT6AzwM',
    appId: '1:725605393327:android:0ef00bae93f3183e80c55a',
    messagingSenderId: '725605393327',
    projectId: 'scientific-research-eb4e5',
    storageBucket: 'scientific-research-eb4e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9PXRlsq3U9OuNBHf9UKeLSv4o1y2BS8k',
    appId: '1:725605393327:ios:304f694b56dc7d0980c55a',
    messagingSenderId: '725605393327',
    projectId: 'scientific-research-eb4e5',
    storageBucket: 'scientific-research-eb4e5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9PXRlsq3U9OuNBHf9UKeLSv4o1y2BS8k',
    appId: '1:725605393327:ios:304f694b56dc7d0980c55a',
    messagingSenderId: '725605393327',
    projectId: 'scientific-research-eb4e5',
    storageBucket: 'scientific-research-eb4e5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBRv0UaZiKa8rYzjVyJDjS8DL3TheJfy8',
    appId: '1:725605393327:web:32c04b2fbb079c7d80c55a',
    messagingSenderId: '725605393327',
    projectId: 'scientific-research-eb4e5',
    authDomain: 'scientific-research-eb4e5.firebaseapp.com',
    storageBucket: 'scientific-research-eb4e5.firebasestorage.app',
    measurementId: 'G-CKTKL21YZH',
  );
}
